server:
  port: 8099
  address: 0.0.0.0
application:
  unidbg:
    dynarmic: false
    verbose: false
    async: true
  http-client:
    connect-timeout-ms: 5000
    read-timeout-ms: 15000
    max-connections: 50
    max-connections-per-route: 20
fq:
  api:
    base-url: https://api5-normal-sinfonlineb.fqnovel.com
    comment-api-base-url: https://api.fqnovel.com
    cookie: store-region=cn-zj; store-region-src=did; install_id=2420480337007787;
    device-pool:
      enabled: true
      size: 5
spring:
  application:
    name: unidbg-boot-server
  profiles:
    active: prod
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        keep-alive: 60s
        max-size: 8
  redis:
    host: 0.0.0.0
    port: 26586
    password: HT5aRYBK2HpReaQuYkLcg
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
