name: Sync Fork Weekly

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    if: github.event.repository.fork

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_FORK_TOKEN }}

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.SYNC_FORK_TOKEN }}
          upstream_sync_repo: mtongle/fqnovel-unidbg
          upstream_sync_branch: main
          target_sync_branch: main
