name: Sync Fork Weekly # 

on:
  # 定时触发器：每周一凌晨 0 点 (UTC时间) 执行一次
  schedule:
    - cron: '0 0 * * 1'
  # 手动触发器：允许你在Actions页面手动执行
  workflow_dispatch:

permissions:
  contents: write # 授权写入仓库代码

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    # 条件判断：此工作流仅在仓库是Fork时运行
    if: github.event.repository.fork
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          # 目标仓库的Token，用于推送代码，使用GitHub自动生成的密钥即可
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 上游仓库的完整路径 (格式: 用户名/仓库名)
          upstream_sync_repo: mtongle/fqnovel-unidbg
          # 要同步的上游分支名称
          upstream_sync_branch: main
          # 目标（你的Fork）分支名称
          target_sync_branch: main
